CREATE TABLE ACCOUNT (
    ACNO NUMBER(10) PRIMARY KEY,
    CNAME VARCHAR2(50),
    BNAME VARCHAR2(50),
    BALANCE NUMBER(12,2)
);


INSERT INTO ACCOUNT VALUES (101, 'Rahul', 'SBI', 25000.50);
INSERT INTO ACCOUNT VALUES (102, 'Priya', 'HDFC', 18000.00);


CREATE OR REPLACE FUNCTION GET_BALANCE(P_ACNO NUMBER)
RETURN NUMBER
IS
    V_BALANCE NUMBER;
BEGIN
    SELECT BALANCE
    INTO V_BALANCE
    FROM ACCOUNT
    WHERE ACNO = P_ACNO;

    RETURN V_BALANCE;
END;
/

